### ISSUE TITLE
Odd issue when trying to run as a door from Synchronet

### ISSUE THREAD

**Issue by realkinetix** [theflyingape/dankdomain#15]
I am trying to get DD to run from Synchronet, and when launching from it, there's an issue with setEncoding, as per:

```
node: /home/sbbs/sbbs/xtrn/dankdomain/node_modules/xvt/lib/xvt.js:109
node: process.stdout.setEncoding(this.encoding);
node: ^
node: TypeError: process.stdout.setEncoding is not a function
node: at _xvt.set emulation [as emulation] (/home/sbbs/sbbs/xtrn/dankdomain/node_modules/xvt/lib/xvt.js:109:24)
node: at new xvt (/home/sbbs/sbbs/xtrn/dankdomain/node_modules/xvt/lib/xvt.js:96:24)
node: at new _xvt (/home/sbbs/sbbs/xtrn/dankdomain/game/lib.js:288:13)
node: at /home/sbbs/sbbs/xtrn/dankdomain/game/lib.js:341:14
node: at Object.<anonymous> (/home/sbbs/sbbs/xtrn/dankdomain/game/lib.js:342:3)
node: at Module._compile (internal/modules/cjs/loader.js:999:30)
node: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
node: at Module.load (internal/modules/cjs/loader.js:863:32)
node: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
node: at Module.require (internal/modules/cjs/loader.js:887:19)
```

Over at https://github.com/pouchdb-community/pouchdb-dump-cli/issues/12 I see a comment that says: "process.stdout.setEncoding exists when process.stdout is of type 'tty', but not when it is of type 'fs'." I'm not sure if this is the sort of thing going on here or not...

DD is being fired up with the following:
Start-up Directory is ../xtrn/dankdomain   (fairly common setup in Synchronet - doors are generally in subfolders of it's 'xtrn' folder)
Command line is: node /sbbs/xtrn/dankdomain/game/main %1
(I put in the full path to try and be sure node was doing the right thing)
And there is the Mystic-style door32.sys being generated - I have altered door.sys to door32.sys in main.js

**Comment by realkinetix** [comment]
Ergh... this was a setup issue, please excuse this.
