### ISSUE TITLE
DD starts as a door but seems to crash with an unhandled promise rejection

### ISSUE THREAD

**Issue by realkinetix** [theflyingape/dankdomain#17]
Right after seeing the Auto Message, DD gives me this:

```
node: (node:25000) UnhandledPromiseRejectionWarning: /home/sbbs/sbbs/xtrn/dankdomain/game/play/menu.js:78
node: if (mainmenu[choice]?.description) {
node: ^
node: SyntaxError: Unexpected token '.'
node: at wrapSafe (internal/modules/cjs/loader.js:915:16)
node: at Module._compile (internal/modules/cjs/loader.js:963:27)
node: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
node: at Module.load (internal/modules/cjs/loader.js:863:32)
node: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
node: at Module.require (internal/modules/cjs/loader.js:887:19)
node: at require (internal/modules/cjs/helpers.js:74:18)
node: at Object.cityguards (/home/sbbs/sbbs/xtrn/dankdomain/game/play/taxman.js:142:9)
node: at Object.cb (/home/sbbs/sbbs/xtrn/dankdomain/game/play/init.js:429:41)
node: at _xvt._read (/home/sbbs/sbbs/xtrn/dankdomain/node_modules/xvt/lib/xvt.js:518:11)
node: (node:25000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
node: (node:25000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by realkinetix** [comment]
Interestingly enough, this happens when running an old version of nodejs.  Closing!
